@HOST = http://localhost:3000/api/v1/auth
@NOW = {{$datetime iso8601}}
@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvYWx4MTdAZ21haWwuY29tIiwiaWF0IjoxNzEwNDYzOTQ5LCJleHAiOjE3MTA0Njc1NDl9.XjAMgI0hqTEqwYnhiDXsTjXnNdsXx_yRYlNEZVtT-SY
@REFRESH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvYWx4MTdAZ21haWwuY29tIiwiaWF0IjoxNzEwNDYzOTQ5LCJleHAiOjE3MTA1NTAzNDl9.65TEi0wSoTV3I6S7FbqQjSa-p73gsSIsKAZhklq1R68

GET {{HOST}}/health-check/ping
###
GET {{HOST}}/dev
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}
###

GET {{HOST}}/roles/lJ8Y1poQ7L
###
GET {{HOST}}/roles?page=1&size=3&name=vip
###
POST {{HOST}}/roles
Content-Type: application/json

[
    {
        "name": "USER"
    },
    {
        "name": "VIP"
    }
]
###
PATCH {{HOST}}/roles/KWko74YeBV
Content-Type: application/json

{
    "name": "ADMINISTRATOR"
}

###
DELETE {{HOST}}/roles/KWko74YeBv

###

POST {{HOST}}/sign-up
Content-Type: application/json

{
    "username": "hoalx18",
    "password": "hoalx18",
    "firstName": "Le",
    "lastName": "Xuan Hoa",
    "birthDay": "{{NOW}}",
    "gender": true,
    "email": "hoalx18@gmail.com",
    "tel": "0364015018",
    "roleId": "rJKE2zEQ1F"
}

###
PATCH {{HOST}}/activate?username=hoalx17&confirmCode=ab789a88-061e-4eba-9d35-ccc4a1d5d6e8
Content-Type: application/json

###
POST {{HOST}}/sign-in
Content-Type: application/json

{
    "username": "hoalx17@gmail.com",
    "password": "hoalx17"
}

###
GET {{HOST}}/me
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

###
GET {{HOST}}/sessions
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

###
PATCH {{HOST}}/deactivate
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "password": "hoalx17"
}

###
DELETE {{HOST}}/sign-out
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

###
DELETE {{HOST}}/delete
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "password": "hoalx17"
}

###
PATCH {{HOST}}/cancel-delete
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "password": "hoalx17"
}

###
DELETE {{HOST}}/sessions
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

###
DELETE {{HOST}}/sessions/KWko74YeBv
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

###
PATCH {{HOST}}/reset-password?username=hoalx17&confirmCode=3a39e77a-275c-46b1-b61f-5a04f1751f7c
Content-Type: application/json

{
    "password": "hoalx18"
}
###
PATCH {{HOST}}/refresh
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}
RefreshToken: Bearer {{REFRESH_TOKEN}}

###
PATCH {{HOST}}/me
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "gender": true
}
###
PATCH {{HOST}}/change-password
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
    "newPassword": "hoalx17"
}

###
